require "tucamar.configs.cmp"
-- require "tucamar.configs.alpha"
-- require "tucamar.configs.lsp"
require "tucamar.configs.telescope"
require "tucamar.configs.treesitter"
require "tucamar.configs.autopairs"
require "tucamar.configs.comment"
require "tucamar.configs.nvim-tree"
require "tucamar.configs.bufferline"
require "tucamar.configs.lualine"
require "tucamar.configs.toggleterm"
