return {
    "akinsho/bufferline.nvim",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    version = "*",
    opts = {
        options = {
            numbers = 'none',
            close_command = 'bdelete! %d',
            right_mouse_command = 'bdelete! %d',
            left_mouse_command = 'buffer %d',
            middle_mouse_command = nil,
            indicator = {
                style = 'icon',
                modified_icon = '●',
                left_trunc_marker = '<-', --'',
                right_trunc_marker = '->', --'',
            },
            offsets = {{filetype = "NvimTree", text = "File Explorer", text_align = "center"}},
            color_icons = true,
            show_buffer_icons = true,
            show_buffer_close_icons = true,
            show_close_icon = true,
            show_tab_indicators = true,
            persist_buffer_sort = true,
            separator_style = "thin",
            enforce_regular_tabs = false,
            always_show_bufferline = true,
            sort_by = 'id',
        },
    },
}
